// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.
// Route generator for file-based routing
// Generates _generated.ts with scanned route definitions

import { runtime, toPosix } from "@eser/standards/runtime";
import * as logging from "@eser/logging";
import type { ScannedRoute, ScanResult } from "./route-scanner.ts";

const generatorLogger = logging.logger.getLogger([
  "laroux-bundler",
  "route-generator",
]);

/**
 * Options for generating route files
 */
export type GenerateRouteOptions = {
  /** Result from scanning routes */
  scanResult: ScanResult;
  /** Path to output the generated file */
  outputPath: string;
  /** Project root directory for relative path calculation */
  projectRoot: string;
  /** Source directory name relative to project root (e.g., "src") */
  srcDirName: string;
};

/**
 * Generates the _generated.ts file with route definitions
 */
export async function generateRouteFile(
  options: GenerateRouteOptions,
): Promise<void> {
  const { scanResult, outputPath, projectRoot, srcDirName } = options;
  const { routes } = scanResult;

  generatorLogger.debug(`Generating routes file: ${outputPath}`);

  const imports: string[] = [];
  const routeDefinitions: string[] = [];

  // Track unique imports to avoid duplicates
  const importedComponents = new Map<string, string>();

  // Create regex to strip srcDir prefix (e.g., "src/" -> "")
  const srcDirPrefix = new RegExp(`^${srcDirName}/`);

  for (const route of routes) {
    // The component path is relative like "src/app/routes/home/page.tsx"
    // We want to import from the bundled file "./app/routes/home/page.js"
    // Bundled files are in dist/server/app/* (not dist/server/src/app/*)
    // Strip .tsx/.ts extension before adding .js
    const componentImportPath = `./${
      route.componentPath.replace(srcDirPrefix, "").replace(/\.tsx?$/, "")
    }.js`;

    // Full path to original source file (for reading export names)
    const componentFullPath = runtime.path.join(
      projectRoot,
      route.componentPath,
    );

    // Get actual export name from source file
    const fallbackComponentName = generateComponentName(route.componentPath);
    const componentName = await getPageExportName(
      componentFullPath,
      fallbackComponentName,
    );

    // Get layout name if exists
    let layoutName: string | undefined;
    if (route.layoutPath) {
      const layoutFullPath = runtime.path.join(projectRoot, route.layoutPath);
      const fallbackLayoutName = generateLayoutName(route.layoutPath);
      layoutName = await getLayoutExportName(
        layoutFullPath,
        fallbackLayoutName,
      );
    }

    // Add component import if not already imported
    if (!importedComponents.has(route.componentPath)) {
      imports.push(
        `import { ${componentName} } from "${componentImportPath}";`,
      );
      importedComponents.set(route.componentPath, componentName);
    }

    // Add layout import if exists
    if (route.layoutPath && layoutName) {
      // Import from bundled files in dist/server/app/ (not dist/server/src/)
      // Strip .tsx/.ts extension before adding .js
      const layoutImportPath = `./${
        route.layoutPath.replace(srcDirPrefix, "").replace(/\.tsx?$/, "")
      }.js`;

      if (!importedComponents.has(route.layoutPath)) {
        imports.push(
          `import { ${layoutName} } from "${layoutImportPath}";`,
        );
        importedComponents.set(route.layoutPath, layoutName);
      }
    }

    // Generate route definition
    const routeDef = generateRouteDefinition(route, componentName, layoutName);
    routeDefinitions.push(routeDef);
  }

  // Generate the file content
  const content = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by laroux-bundler/route-generator.ts
// Run build to regenerate

import type { RouteDefinition } from "@eser/laroux/router";
${imports.join("\n")}

/**
 * Auto-generated routes from file-based routing
 * Routes are sorted by specificity (static > dynamic > catch-all)
 */
export const generatedRoutes: RouteDefinition[] = [
${routeDefinitions.map((r) => `  ${r}`).join(",\n")},
];
`;

  await runtime.fs.writeTextFile(outputPath, content);
  generatorLogger.debug(`Generated ${routes.length} route(s)`);
}

/**
 * Generates the api-routes.ts file with API route definitions
 */
export async function generateApiRouteFile(
  scanResult: ScanResult,
  outputPath: string,
  projectRoot: string,
): Promise<void> {
  const { apiRoutes } = scanResult;

  if (apiRoutes.length === 0) {
    generatorLogger.debug("No API routes found, skipping generation");
    return;
  }

  generatorLogger.debug(`Generating API routes file: ${outputPath}`);

  const routeEntries: string[] = [];

  for (const route of apiRoutes) {
    // Calculate import path relative to output directory
    const outputDir = runtime.path.dirname(outputPath);
    const modulePath = getRelativeImportPath(
      outputDir,
      runtime.path.join(projectRoot, route.componentPath),
    );

    routeEntries.push(
      `  { path: "${route.routePath}", modulePath: "${modulePath}" }`,
    );
  }

  const content = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by laroux-bundler/route-generator.ts

export type ApiRouteDefinition = {
  path: string;
  modulePath: string;
};

/**
 * Auto-generated API routes from file-based routing
 */
export const apiRoutes: ApiRouteDefinition[] = [
${routeEntries.join(",\n")},
];
`;

  await runtime.fs.writeTextFile(outputPath, content);
  generatorLogger.debug(`Generated ${apiRoutes.length} API route(s)`);
}

/**
 * Generates the proxy-registry.ts file with proxy definitions
 */
export async function generateProxyFile(
  scanResult: ScanResult,
  outputPath: string,
  projectRoot: string,
): Promise<void> {
  const { proxies } = scanResult;

  if (proxies.length === 0) {
    generatorLogger.debug("No proxies found, skipping generation");
    return;
  }

  generatorLogger.debug(`Generating proxy registry file: ${outputPath}`);

  const proxyEntries: string[] = [];

  for (const proxy of proxies) {
    // Calculate import path relative to output directory
    const outputDir = runtime.path.dirname(outputPath);
    const modulePath = getRelativeImportPath(
      outputDir,
      runtime.path.join(projectRoot, proxy.modulePath),
    );

    proxyEntries.push(
      `  { pathPrefix: "${proxy.pathPrefix}", modulePath: "${modulePath}" }`,
    );
  }

  const content = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by laroux-bundler/route-generator.ts

export type ProxyDefinition = {
  pathPrefix: string;
  modulePath: string;
};

/**
 * Auto-generated proxy definitions from file-based routing
 * Sorted by path prefix length (most specific first)
 */
export const proxyRegistry: ProxyDefinition[] = [
${proxyEntries.join(",\n")},
];
`;

  await runtime.fs.writeTextFile(outputPath, content);
  generatorLogger.debug(`Generated ${proxies.length} proxy definition(s)`);
}

/**
 * Extract all export names from a React component file
 * Finds all named exports and default export
 */
async function extractExportNames(filePath: string): Promise<string[]> {
  try {
    const content = await runtime.fs.readTextFile(filePath);
    const exportNames: string[] = [];

    // Match all: export function ComponentName() or export async function ComponentName()
    const namedFunctionMatches = content.matchAll(
      /export\s+(?:async\s+)?function\s+(\w+)/g,
    );
    for (const match of namedFunctionMatches) {
      if (match[1] !== undefined) {
        exportNames.push(match[1]);
      }
    }

    // Match all: export const ComponentName =
    const namedConstMatches = content.matchAll(/export\s+const\s+(\w+)\s*=/g);
    for (const match of namedConstMatches) {
      if (match[1] !== undefined) {
        exportNames.push(match[1]);
      }
    }

    // Check for default export
    if (content.match(/export\s+default\s+/)) {
      exportNames.push("default");
    }

    // Deduplicate and return
    return [...new Set(exportNames)];
  } catch {
    return [];
  }
}

/**
 * Gets the main page export name from a file
 * Prefers named exports ending with "Page", falls back to first named export
 */
async function getPageExportName(
  filePath: string,
  fallbackName: string,
): Promise<string> {
  const exports = await extractExportNames(filePath);

  if (exports.length === 0) {
    return fallbackName;
  }

  // Prefer export ending with "Page" (non-default)
  const pageExport = exports.find((e) => e !== "default" && e.endsWith("Page"));
  if (pageExport) {
    return pageExport;
  }

  // Otherwise use first non-default export
  const namedExport = exports.find((e) => e !== "default");
  if (namedExport) {
    return namedExport;
  }

  // Fall back to generated name
  return fallbackName;
}

/**
 * Gets the main layout export name from a file
 * Prefers named exports ending with "Layout", falls back to first named export
 */
async function getLayoutExportName(
  filePath: string,
  fallbackName: string,
): Promise<string> {
  const exports = await extractExportNames(filePath);

  if (exports.length === 0) {
    return fallbackName;
  }

  // Prefer export ending with "Layout" (non-default)
  const layoutExport = exports.find(
    (e) => e !== "default" && e.endsWith("Layout"),
  );
  if (layoutExport) {
    return layoutExport;
  }

  // Otherwise use first non-default export
  const namedExport = exports.find((e) => e !== "default");
  if (namedExport) {
    return namedExport;
  }

  // Fall back to generated name
  return fallbackName;
}

/**
 * Generates a PascalCase component name from file path (fallback)
 */
function generateComponentName(componentPath: string): string {
  // Get directory name (e.g., "stories", "[slug]", "home")
  const dirName = runtime.path.basename(runtime.path.dirname(componentPath));

  // Convert to PascalCase
  const baseName = toPascalCase(cleanDynamicSegment(dirName));

  return `${baseName}Page`;
}

/**
 * Generates a PascalCase layout name from file path (fallback)
 */
function generateLayoutName(layoutPath: string): string {
  const dirName = runtime.path.basename(runtime.path.dirname(layoutPath));
  const baseName = toPascalCase(cleanDynamicSegment(dirName));
  return `${baseName}Layout`;
}

/**
 * Cleans dynamic segment brackets from a string
 * [slug] -> slug
 * [...slug] -> slug
 */
function cleanDynamicSegment(str: string): string {
  // Handle catch-all [...slug]
  if (str.startsWith("[...")) {
    return str.slice(4, -1);
  }
  // Handle dynamic [slug]
  if (str.startsWith("[") && str.endsWith("]")) {
    return str.slice(1, -1);
  }
  return str;
}

/**
 * Converts a string to PascalCase
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join("");
}

/**
 * Gets relative import path from output directory to target file
 */
function getRelativeImportPath(fromDir: string, toFile: string): string {
  // Get relative path and convert to POSIX format for import specifiers
  const relativePath = toPosix(runtime.path.relative(fromDir, toFile));

  // Add ./ prefix if needed for relative imports
  if (!relativePath.startsWith(".")) {
    return `./${relativePath}`;
  }

  return relativePath;
}

/**
 * Generates a route definition object string
 */
function generateRouteDefinition(
  route: ScannedRoute,
  componentName: string,
  layoutName?: string,
): string {
  const parts: string[] = [
    `path: "${route.routePath}"`,
    `component: ${componentName}`,
  ];

  if (layoutName) {
    parts.push(`layout: ${layoutName}`);
  }

  return `{ ${parts.join(", ")} }`;
}
