// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Bash shell completion generator
 *
 * @module
 */

import type { CompletionFlag, CompletionNode } from "../types.ts";

const generateFlagCompletions = (flags: readonly CompletionFlag[]): string => {
  const parts: string[] = [];

  for (const flag of flags) {
    parts.push(`--${flag.name}`);
    if (flag.short !== undefined) {
      parts.push(`-${flag.short}`);
    }
  }

  return parts.join(" ");
};

const generateSubcommandCase = (
  node: CompletionNode,
  prefix: string,
): string => {
  if (node.children === undefined || node.children.length === 0) {
    return "";
  }

  const subcommandNames = node.children.map((c) => c.name).join(" ");
  const flagCompletions = node.flags !== undefined
    ? generateFlagCompletions(node.flags)
    : "";

  const completions = [subcommandNames, flagCompletions]
    .filter((s) => s.length > 0)
    .join(" ");

  let output = `        ${prefix})\n`;
  output +=
    `            COMPREPLY=( $(compgen -W "${completions}" -- "\${cur}") )\n`;
  output += `            return 0\n`;
  output += `            ;;\n`;

  // Generate nested cases for children
  for (const child of node.children) {
    if (child.children !== undefined && child.children.length > 0) {
      output += generateSubcommandCase(child, `${prefix} ${child.name}`);
    }
  }

  return output;
};

/**
 * Generate a bash completion script for the given command tree
 */
export const generate = (appName: string, tree: CompletionNode): string => {
  const topLevelCommands = tree.children?.map((c) => c.name).join(" ") ?? "";
  const topLevelFlags = tree.flags !== undefined
    ? generateFlagCompletions(tree.flags)
    : "";

  const topLevel = [topLevelCommands, topLevelFlags]
    .filter((s) => s.length > 0)
    .join(" ");

  let caseClauses = "";
  if (tree.children !== undefined) {
    for (const child of tree.children) {
      caseClauses += generateSubcommandCase(child, child.name);
    }
  }

  return `# ${appName} bash completion
# Generated by @eser/shell/completions

_${appName}_completions() {
    local cur prev words cword
    _init_completion || return

    COMPREPLY=()
    cur="\${COMP_WORDS[COMP_CWORD]}"
    prev="\${COMP_WORDS[COMP_CWORD-1]}"

    # Build the command path from words
    local cmd_path=""
    local i
    for ((i=1; i<COMP_CWORD; i++)); do
        case "\${COMP_WORDS[i]}" in
            -*)
                # Skip flags
                ;;
            *)
                if [[ -n "$cmd_path" ]]; then
                    cmd_path="$cmd_path \${COMP_WORDS[i]}"
                else
                    cmd_path="\${COMP_WORDS[i]}"
                fi
                ;;
        esac
    done

    case "$cmd_path" in
${caseClauses}        "")
            COMPREPLY=( $(compgen -W "${topLevel}" -- "\${cur}") )
            return 0
            ;;
    esac
}

complete -F _${appName}_completions ${appName}
`;
};
