// Code generated by "stringer -type ConnectionState -trimprefix ConnectionState"; DO NOT EDIT.

package connfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ConnectionStateNotInitialized-0]
	_ = x[ConnectionStateConnected-1]
	_ = x[ConnectionStateLive-2]
	_ = x[ConnectionStateReady-3]
	_ = x[ConnectionStateDisconnected-4]
	_ = x[ConnectionStateError-5]
	_ = x[ConnectionStateReconnecting-6]
}

const _ConnectionState_name = "NotInitializedConnectedLiveReadyDisconnectedErrorReconnecting"

var _ConnectionState_index = [...]uint8{0, 14, 23, 27, 32, 44, 49, 61}

func (i ConnectionState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ConnectionState_index)-1 {
		return "ConnectionState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ConnectionState_name[_ConnectionState_index[idx]:_ConnectionState_index[idx+1]]
}
