// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Generate the per-package `deno.json` JSR publish manifests.
 *
 * ## Why this exists
 *
 * Every package used to carry two config files whose `exports` maps were
 * byte-identical -- `@eserstack/fp` repeated the same 51 entries in both. That
 * doubling is what made a one-line version change rewrite ~70 files per
 * release, and it had already drifted once (`noskills/package.json` exported
 * `./session`; its `deno.json` did not).
 *
 * Per-package `deno.json` turns out to be *only* a JSR publish manifest:
 * removing them leaves `deno check` and `deno test` (2148 tests) untouched,
 * because module resolution runs through `package.json`'s `workspaces` field
 * plus the pnpm symlinks in node_modules. So they are generated here rather
 * than hand-maintained.
 *
 * ## Source of truth
 *
 *   name, exports  <- the package's own package.json
 *   version        <- the repo-root VERSION file
 *   publish, tasks <- a committed `deno.extra.json`, when one exists
 *
 * `publish.include` (the laroux family) and `tasks` (posts) have no
 * package.json equivalent -- package.json carries neither `files` nor
 * `scripts` for those packages -- so they stay committed in `deno.extra.json`
 * and are merged in here. Everything else is derived.
 *
 * ## Usage
 *
 *   deno run -A etc/scripts/gen-jsr-manifests.ts           # write manifests
 *   deno run -A etc/scripts/gen-jsr-manifests.ts --check    # verify, exit 1 on drift
 *   deno run -A etc/scripts/gen-jsr-manifests.ts --clean    # remove generated manifests
 *
 * @module
 */

import { runtime } from "@eserstack/standards/cross-runtime";
import * as stdPath from "@std/path";

const REPO_ROOT = stdPath.resolve(
  stdPath.dirname(stdPath.fromFileUrl(import.meta.url)),
  "../..",
);

const PACKAGES_DIR = stdPath.join(REPO_ROOT, "pkg/@eserstack");

/** Marker so a human (or a stray `git add`) can tell these are derived. */
const GENERATED_NOTE =
  "GENERATED by etc/scripts/gen-jsr-manifests.ts -- do not edit. " +
  "Edit package.json (name/exports) or deno.extra.json (publish/tasks) instead.";

type Manifest = {
  "//": string;
  name: string;
  version: string;
  exports: unknown;
  [key: string]: unknown;
};

const readJson = async (path: string): Promise<Record<string, unknown>> => {
  const text = await runtime.fs.readTextFile(path);

  return JSON.parse(text) as Record<string, unknown>;
};

const exists = async (path: string): Promise<boolean> => {
  try {
    await runtime.fs.stat(path);

    return true;
  } catch {
    return false;
  }
};

/** Build one package's manifest, or null when the package is not publishable. */
const buildManifest = async (
  pkgDir: string,
  version: string,
): Promise<Manifest | null> => {
  const pkgJsonPath = stdPath.join(pkgDir, "package.json");

  if (!(await exists(pkgJsonPath))) {
    return null;
  }

  const pkg = await readJson(pkgJsonPath);

  const name = pkg["name"];
  const exports = pkg["exports"];

  // A package with no name or no exports is not something JSR can publish.
  if (typeof name !== "string" || exports === undefined) {
    return null;
  }

  const manifest: Manifest = {
    "//": GENERATED_NOTE,
    name,
    version,
    exports,
  };

  // Merge the irreducible bits that package.json cannot express.
  const extraPath = stdPath.join(pkgDir, "deno.extra.json");

  if (await exists(extraPath)) {
    const extra = await readJson(extraPath);

    for (const [key, value] of Object.entries(extra)) {
      if (key === "//") {
        continue;
      }

      manifest[key] = value;
    }
  }

  return manifest;
};

const serialize = (manifest: Manifest): string =>
  JSON.stringify(manifest, null, 2) + "\n";

const listPackageDirs = async (): Promise<string[]> => {
  const dirs: string[] = [];

  for await (const entry of runtime.fs.readDir(PACKAGES_DIR)) {
    if (!entry.isDirectory) {
      continue;
    }

    dirs.push(stdPath.join(PACKAGES_DIR, entry.name));
  }

  return dirs.sort();
};

const main = async (): Promise<void> => {
  const args = runtime.process.args as string[];
  const check = args.includes("--check");
  const clean = args.includes("--clean");

  const version =
    (await runtime.fs.readTextFile(stdPath.join(REPO_ROOT, "VERSION")))
      .trim();

  const dirs = await listPackageDirs();

  let written = 0;
  let skipped = 0;
  const drifted: string[] = [];

  for (const dir of dirs) {
    const target = stdPath.join(dir, "deno.json");
    const manifest = await buildManifest(dir, version);

    if (manifest === null) {
      skipped++;

      // A stale manifest for a now-unpublishable package is still drift.
      if (clean && (await exists(target))) {
        await runtime.fs.remove(target);
      }

      continue;
    }

    const expected = serialize(manifest);

    if (clean) {
      if (await exists(target)) {
        await runtime.fs.remove(target);
        written++;
      }

      continue;
    }

    if (check) {
      const actual = (await exists(target))
        ? await runtime.fs.readTextFile(target)
        : "";

      if (actual !== expected) {
        drifted.push(stdPath.relative(REPO_ROOT, target));
      }

      continue;
    }

    await runtime.fs.writeTextFile(target, expected);
    written++;
  }

  if (check) {
    if (drifted.length > 0) {
      console.error(
        `JSR manifests are stale (${drifted.length}):\n` +
          drifted.map((d) => `  ${d}`).join("\n") +
          `\n\nRun: deno run -A etc/scripts/gen-jsr-manifests.ts`,
      );
      Deno.exitCode = 1;

      return;
    }

    console.log(
      `JSR manifests up to date (${
        dirs.length - skipped
      } packages, v${version}).`,
    );

    return;
  }

  const verb = clean ? "Removed" : "Generated";
  console.log(
    `${verb} ${written} JSR manifest(s) at v${version} (${skipped} package(s) not publishable).`,
  );
};

await main();
