// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Git hook installation — installs, uninstalls, and reports status of
 * managed git hooks derived from `.eser/manifest.yml` workflow events.
 *
 * @module
 */

import * as cliParseArgs from "@std/cli/parse-args";
import * as span from "@eser/streams/span";
import * as streams from "@eser/streams";
import * as primitives from "@eser/primitives";
import * as standards from "@eser/standards";
import * as configManifest from "@eser/config/manifest";
import type * as shellArgs from "@eser/shell/args";

// =============================================================================
// Constants
// =============================================================================

/** Maps manifest event names to git hook filenames and extra shell args. */
const EVENT_TO_HOOK: Record<string, { hookName: string; args: string }> = {
  precommit: { hookName: "pre-commit", args: "" },
  commitmsg: { hookName: "commit-msg", args: '-- "$1"' },
  prepush: { hookName: "pre-push", args: "" },
};

/** Marker comment placed in managed hook scripts. */
const MARKER = "# @eser managed hook";

// =============================================================================
// Helpers
// =============================================================================

/**
 * Generate the shell script content for a git hook.
 *
 * Uses `getCliCommand()` to detect the best available command at generation
 * time: eser binary > npx > pnpx > bunx > deno run jsr: > "eser" fallback.
 */
const generateHookScript = async (
  event: string,
  args: string,
): Promise<string> => {
  const cliCmd = await standards.crossRuntime.getCliCommand({
    command: "eser",
    devCommand: "deno task cli",
    npmPackage: "eser",
    jsrPackage: "@eser/cli",
  });
  const argsStr = args.length > 0 ? ` ${args}` : "";
  const command = `${cliCmd} workflows run -e ${event}${argsStr}`;

  return [
    "#!/bin/sh",
    `${MARKER} — generated by \`eser codebase install\``,
    "# Do not edit. Re-run `eser codebase install` to update.",
    "",
    command,
    "",
  ].join("\n");
};

/**
 * Locate the `.git` directory for the current repository.
 */
const findGitDir = async (): Promise<string | null> => {
  try {
    const output = await standards.crossRuntime.runtime.exec.exec(
      "git",
      ["rev-parse", "--git-dir"],
    );
    const dir = output.trim();
    if (dir.length > 0) return dir;
  } catch {
    // fall through
  }

  // Fallback: check cwd
  const cwd = standards.crossRuntime.runtime.process.cwd();
  const dotGit = standards.crossRuntime.runtime.path.join(cwd, ".git");
  try {
    const info = await standards.crossRuntime.runtime.fs.stat(dotGit);
    if (info.isDirectory) return dotGit;
  } catch {
    // not found
  }

  return null;
};

/**
 * Extract unique events from a manifest's workflows array.
 */
const extractEvents = (
  raw: Record<string, unknown>,
): string[] => {
  const workflows = raw["workflows"] as
    | readonly { on?: readonly string[] }[]
    | undefined;
  if (!Array.isArray(workflows)) return [];

  const events = new Set<string>();
  for (const wf of workflows) {
    if (Array.isArray(wf.on)) {
      for (const ev of wf.on) {
        if (typeof ev === "string") events.add(ev);
      }
    }
  }
  return [...events];
};

// =============================================================================
// Renderer for string returns
// =============================================================================

const renderer = streams.renderers.ansi();

// =============================================================================
// Install
// =============================================================================

/**
 * Install managed git hooks based on `.eser/manifest.yml` workflow events.
 *
 * Flags:
 *   --force     Overwrite non-managed hooks
 *   --dry-run   Show what would happen without writing
 *   --help      Show usage
 */
export const main = async (
  cliArgs?: readonly string[],
): Promise<shellArgs.CliResult<void>> => {
  const parsed = cliParseArgs.parseArgs((cliArgs ?? []) as string[], {
    boolean: ["force", "dry-run", "help"],
    alias: { h: "help", f: "force", n: "dry-run" },
  });

  if (parsed.help) {
    console.log(
      "eser codebase install — Install git hooks from .eser/manifest.yml",
    );
    console.log("");
    console.log("Flags:");
    console.log("  --force, -f     Overwrite non-managed hooks");
    console.log("  --dry-run, -n   Show what would happen without writing");
    console.log("  --help, -h      Show this help");
    return primitives.results.ok(undefined);
  }

  const out = streams.output({
    renderer,
    sink: streams.sinks.stdout(),
  });

  const force = parsed.force as boolean;
  const dryRun = parsed["dry-run"] as boolean;

  // 1. Find .git directory
  const gitDir = await findGitDir();
  if (gitDir === null) {
    out.writeln(span.red("Error: not inside a git repository"));
    await out.close();
    return primitives.results.fail({ exitCode: 1 });
  }

  const hooksDir = standards.crossRuntime.runtime.path.join(gitDir, "hooks");

  // 2. Load manifest
  const cwd = standards.crossRuntime.runtime.process.cwd();
  const raw = await configManifest.loadManifest(cwd);
  if (raw === null) {
    out.writeln(
      span.red("Error: no .eser/manifest.yml found in current directory"),
    );
    await out.close();
    return primitives.results.fail({ exitCode: 1 });
  }

  // 3. Extract events
  const events = extractEvents(raw);
  if (events.length === 0) {
    out.writeln(
      span.yellow("No workflow events found — nothing to install."),
    );
    await out.close();
    return primitives.results.ok(undefined);
  }

  // 4. Ensure hooks directory exists
  if (!dryRun) {
    await standards.crossRuntime.runtime.fs.ensureDir(hooksDir);
  }

  // 5. Install hooks
  let installed = 0;
  let skipped = 0;
  let updated = 0;

  for (const event of events) {
    const mapping = EVENT_TO_HOOK[event];
    if (mapping === undefined) {
      out.writeln(
        span.dim(`  skip  ${event} (unknown event, no hook mapping)`),
      );
      continue;
    }

    const { hookName, args } = mapping;
    const hookPath = standards.crossRuntime.runtime.path.join(
      hooksDir,
      hookName,
    );
    const script = await generateHookScript(event, args);

    let exists = false;
    let isManaged = false;

    try {
      const existing = await standards.crossRuntime.runtime.fs.readTextFile(
        hookPath,
      );
      exists = true;
      isManaged = existing.includes(MARKER);
    } catch {
      // file does not exist
    }

    if (dryRun) {
      if (!exists) {
        out.writeln(
          span.blue(`  would create  ${hookName}`),
        );
      } else if (isManaged) {
        out.writeln(
          span.blue(`  would update  ${hookName} (managed)`),
        );
      } else if (force) {
        out.writeln(
          span.yellow(`  would overwrite  ${hookName} (--force)`),
        );
      } else {
        out.writeln(
          span.yellow(
            `  would skip  ${hookName} (user hook; use --force to overwrite)`,
          ),
        );
      }
      continue;
    }

    if (exists && !isManaged && !force) {
      out.writeln(
        span.yellow(
          `  skip  ${hookName} — user hook exists (use --force to overwrite)`,
        ),
      );
      skipped++;
      continue;
    }

    await standards.crossRuntime.runtime.fs.writeTextFile(hookPath, script);

    // chmod +x (non-fatal on platforms without chmod support)
    try {
      await standards.crossRuntime.runtime.fs.chmod(hookPath, 0o755);
    } catch {
      // Windows doesn't support chmod — hook will still work via shebang
    }

    if (exists && isManaged) {
      out.writeln(
        span.green(`  updated  ${hookName}`),
      );
      updated++;
    } else {
      out.writeln(
        span.green(`  installed  ${hookName}`),
      );
      installed++;
    }
  }

  // Summary
  out.writeln();
  const parts: string[] = [];
  if (installed > 0) parts.push(`${installed} installed`);
  if (updated > 0) parts.push(`${updated} updated`);
  if (skipped > 0) parts.push(`${skipped} skipped`);
  if (dryRun) {
    out.writeln(span.dim("(dry run — no changes made)"));
  } else if (parts.length > 0) {
    out.writeln(span.green(`Done: ${parts.join(", ")}.`));
  } else {
    out.writeln(span.dim("Nothing to do."));
  }

  await out.close();
  return primitives.results.ok(undefined);
};

// =============================================================================
// Uninstall
// =============================================================================

/**
 * Remove all managed git hooks (those containing the `@eser managed hook` marker).
 */
export const uninstallMain = async (
  cliArgs?: readonly string[],
): Promise<shellArgs.CliResult<void>> => {
  const parsed = cliParseArgs.parseArgs((cliArgs ?? []) as string[], {
    boolean: ["help"],
    alias: { h: "help" },
  });

  if (parsed.help) {
    console.log("eser codebase uninstall — Remove managed git hooks");
    return primitives.results.ok(undefined);
  }

  const out = streams.output({
    renderer,
    sink: streams.sinks.stdout(),
  });

  const gitDir = await findGitDir();
  if (gitDir === null) {
    out.writeln(span.red("Error: not inside a git repository"));
    await out.close();
    return primitives.results.fail({ exitCode: 1 });
  }

  const hooksDir = standards.crossRuntime.runtime.path.join(gitDir, "hooks");
  let removed = 0;

  // Iterate over known hook names
  const knownHooks = Object.values(EVENT_TO_HOOK).map((m) => m.hookName);
  const uniqueHooks = [...new Set(knownHooks)];

  for (const hookName of uniqueHooks) {
    const hookPath = standards.crossRuntime.runtime.path.join(
      hooksDir,
      hookName,
    );
    try {
      const content = await standards.crossRuntime.runtime.fs.readTextFile(
        hookPath,
      );
      if (content.includes(MARKER)) {
        await standards.crossRuntime.runtime.fs.remove(hookPath);
        out.writeln(span.green(`  removed  ${hookName}`));
        removed++;
      }
    } catch {
      // file doesn't exist — skip
    }
  }

  out.writeln();
  if (removed > 0) {
    out.writeln(span.green(`Done: ${removed} hook(s) removed.`));
  } else {
    out.writeln(span.dim("No managed hooks found."));
  }

  await out.close();
  return primitives.results.ok(undefined);
};

// =============================================================================
// Status
// =============================================================================

/**
 * Show the installation status of git hooks expected by the manifest.
 */
export const statusMain = async (
  cliArgs?: readonly string[],
): Promise<shellArgs.CliResult<void>> => {
  const parsed = cliParseArgs.parseArgs((cliArgs ?? []) as string[], {
    boolean: ["help"],
    alias: { h: "help" },
  });

  if (parsed.help) {
    console.log("eser codebase status — Show git hook installation status");
    return primitives.results.ok(undefined);
  }

  const out = streams.output({
    renderer,
    sink: streams.sinks.stdout(),
  });

  const gitDir = await findGitDir();
  if (gitDir === null) {
    out.writeln(span.red("Error: not inside a git repository"));
    await out.close();
    return primitives.results.fail({ exitCode: 1 });
  }

  const hooksDir = standards.crossRuntime.runtime.path.join(gitDir, "hooks");

  // Load manifest
  const cwd = standards.crossRuntime.runtime.process.cwd();
  const raw = await configManifest.loadManifest(cwd);
  if (raw === null) {
    out.writeln(
      span.red("Error: no .eser/manifest.yml found in current directory"),
    );
    await out.close();
    return primitives.results.fail({ exitCode: 1 });
  }

  const events = extractEvents(raw);
  if (events.length === 0) {
    out.writeln(span.dim("No workflow events found in manifest."));
    await out.close();
    return primitives.results.ok(undefined);
  }

  out.writeln(span.bold("Git hook status:"));
  out.writeln();

  for (const event of events) {
    const mapping = EVENT_TO_HOOK[event];
    if (mapping === undefined) {
      out.writeln(
        span.text("  "),
        span.dim(event.padEnd(14)),
        span.text(" "),
        span.dim("(no hook mapping)"),
      );
      continue;
    }

    const { hookName } = mapping;
    const hookPath = standards.crossRuntime.runtime.path.join(
      hooksDir,
      hookName,
    );

    let statusSpan: span.Span;
    try {
      const content = await standards.crossRuntime.runtime.fs.readTextFile(
        hookPath,
      );
      if (content.includes(MARKER)) {
        statusSpan = span.green("managed (@eser)");
      } else {
        statusSpan = span.yellow("user hook");
      }
    } catch {
      statusSpan = span.dim("not installed");
    }

    out.writeln(span.text(`  ${hookName.padEnd(14)} `), statusSpan);
  }

  out.writeln();
  await out.close();
  return primitives.results.ok(undefined);
};

// =============================================================================
// Direct execution
// =============================================================================

if (import.meta.main) {
  const { runCliMain } = await import("./cli-support.ts");
  runCliMain(
    await main(standards.crossRuntime.runtime.process.args as string[]),
  );
}
