import { isAlphanumeric } from "../checks/is-alphanumeric.ts";
import { isNumeric } from "../checks/is-numeric.ts";
import { isWhitespace } from "../checks/is-whitespace.ts";
import { type TokenDefinitions } from "./definition.ts";

export const simpleTokens: TokenDefinitions = {
  T_NEWLINE: ["T_NEWLINE", "\n"],
  T_DOT: ["T_DOT", "."],
  T_COMMA: ["T_COMMA", ","],
  T_COLON: ["T_COLON", ":"],
  T_SEMICOLON: ["T_SEMICOLON", ";"],
  T_OPEN_BRACKET: ["T_OPEN_BRACKET", "("],
  T_CLOSE_BRACKET: ["T_CLOSE_BRACKET", ")"],
  T_OPEN_SQUARE_BRACKET: ["T_OPEN_SQUARE_BRACKET", "["],
  T_CLOSE_SQUARE_BRACKET: ["T_CLOSE_SQUARE_BRACKET", "]"],
  T_OPEN_CURLY_BRACKET: ["T_OPEN_CURLY_BRACKET", "{"],
  T_CLOSE_CURLY_BRACKET: ["T_CLOSE_CURLY_BRACKET", "}"],
  T_UNDERSCORE: ["T_UNDERSCORE", "_"],
  T_QUESTION_MARK: ["T_QUESTION_MARK", "?"],
  T_AT: ["T_AT", "@"],
  T_PLUS: ["T_PLUS", "+"],
  T_HYPHEN: ["T_HYPHEN", "-"],
  T_ASTERISK: ["T_ASTERISK", "*"],
  T_SLASH: ["T_SLASH", "/"],
  T_PERCENT: ["T_PERCENT", "%"],
  T_AMPERSAND: ["T_AMPERSAND", "&"],
  T_PIPE: ["T_PIPE", "|"],
  T_TILDE: ["T_TILDE", "~"],
  T_CARET: ["T_CARET", "^"],
  T_IS_SMALLER: ["T_IS_SMALLER", "<"],
  T_IS_GREATER: ["T_IS_GREATER", ">"],
  T_EQUAL: ["T_EQUAL", "="],
  T_BACKSLASH: ["T_BACKSLASH", "\\"],
  T_DOUBLE_QUOTE: ["T_DOUBLE_QUOTE", '"'],
  T_QUOTE: ["T_QUOTE", "'"],
  T_BACKTICK: ["T_BACKTICK", "`"],
  T_DOLLAR_SIGN: ["T_DOLLAR_SIGN", "$"],
  T_WHITESPACE: ["T_WHITESPACE", isWhitespace],
  T_NUMERIC: ["T_NUMERIC", isNumeric],
  T_ALPHANUMERIC: ["T_ALPHANUMERIC", isAlphanumeric],
  T_UNKNOWN: ["T_UNKNOWN", ""],
  T_END: ["T_END", ""],
};
