// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Kiro adapter — implements ToolAdapter for Kiro, generating multi-file
 * steering documents under `.kiro/steering/` with YAML frontmatter inclusion
 * modes.
 *
 * @module
 */

import type * as adapter from "../adapter.ts";
import * as crossRuntime from "@eser/standards/cross-runtime";

// =============================================================================
// Steering File Paths
// =============================================================================

const STEERING_DIR = ".kiro/steering";
const HOOKS_DIR = ".kiro/settings";
const AGENTS_DIR = ".kiro/agents";
const SPECS_DIR = ".kiro/specs";
const HOOKS_FILE = "hooks.json";
const MCP_FILE = "mcp.json";
const PROTOCOL_FILE = "noskills-protocol.md";
const COACHING_FILE = "noskills-coaching.md";
const RULES_FILE = "noskills-rules.md";
const LEGACY_FILE = "conventions.md";
const EXECUTOR_FILE = "noskills-executor.json";
const VERIFIER_FILE = "noskills-verifier.json";

// =============================================================================
// Steering Content Generators
// =============================================================================

const buildProtocol = (
  commandPrefix: string,
  options?: adapter.SyncOptions,
): string => {
  const lines = [
    "---",
    "inclusion: always",
    "---",
    "",
    "# noskills Protocol",
    "",
    "# Generated by noskills — do not edit manually",
    "",
    "## What is noskills",
    "",
    "This project uses noskills for state-driven orchestration.",
    "Do NOT read `.eser/rules/`, `.eser/specs/`, or concern files directly.",
    "noskills gives you exactly what you need via JSON output.",
    "",
    "## Protocol",
    "",
    `    ${commandPrefix} next --spec=<name>                           # get current instruction`,
    `    ${commandPrefix} next --spec=<name> --answer="your response"  # submit result and advance`,
    "",
    "Every noskills command that operates on a spec MUST include `--spec=<name>`.",
    `Never omit it. Use \`${commandPrefix} spec list\` to see available specs.`,
    "",
    "## When to call noskills next",
    "",
    `You MUST call \`${commandPrefix} next\` in these situations:`,
    "",
    "1. At the **START** of every conversation (first thing you do)",
    "2. **BEFORE** creating or modifying any file (to verify you have an active task)",
    "3. **AFTER** completing a logical unit of work (to report progress)",
    "4. When you encounter a **DECISION** that affects architecture or scope",
    "5. When you are **UNSURE** what to do next",
    "",
    "NEVER proceed with implementation without checking noskills first.",
    "NEVER make architectural decisions independently — noskills routes them to the user.",
  ];

  if (!(options?.allowGit ?? false)) {
    lines.push(
      "",
      "## Git is read-only",
      "",
      "You MUST NOT run git write commands: commit, add, push, checkout, stash,",
      "reset, merge, rebase, cherry-pick. The user controls git. You control files.",
      "You MAY read from git: log, diff, status, show, blame.",
    );
  }

  lines.push(
    "",
    "## Interactive choices",
    "",
    "Present choices as numbered lists. Users select by number.",
    "When interactiveOptions are present in noskills output, present each as a",
    "numbered item with its label and description. Ask the user to pick a number.",
    "Use the `commandMap` to resolve the user's selection to a CLI command.",
    "",
    "## Decision principle: Explicit > Clever",
    "",
    "You NEVER skip steps, bypass questions, or make assumptions on behalf of the user.",
    "- Discovery questions → ask the user, don't answer yourself",
    "- Classification → ask the user, don't infer",
    "- Spec approval → ask the user, don't auto-approve",
    "- Task refinement → ask the user, don't self-assign",
    "- Rule promotion → ask the user, don't decide",
    'If you think something can be skipped, ASK "would you like to skip this?" — don\'t skip it.',
    "",
    "## Command execution",
    "",
    "When told to run a noskills command, execute it IMMEDIATELY. Do not explore,",
    "research, read source code, or plan first. The command output contains all the",
    "context you need. Exploring noskills internals wastes tokens and delays the user.",
    "",
    "## JSON output",
    "",
    "noskills returns JSON with a `phase` field and phase-specific instructions.",
    "The `meta` block contains resume context - use it to orient yourself,",
    "especially after compaction or at the start of a new session.",
    "Follow the `instruction` field. Use `transition` commands to advance state.",
    "",
  );

  return lines.join("\n");
};

const buildCoaching = (commandPrefix: string): string => {
  const lines = [
    "---",
    "inclusion: auto",
    "name: noskills-coaching",
    'description: "Guidance for noskills spec-driven development workflow, including convention discovery and rule promotion"',
    "---",
    "",
    "# noskills Coaching",
    "",
    "# Generated by noskills — do not edit manually",
    "",
    "## Convention discovery",
    "",
    "When you discover a pattern, receive a correction, or identify a recurring",
    'preference from the user, ask: "Should this be a permanent rule for this',
    `project, or just for this task?" If permanent, run: \`${commandPrefix} rule add`,
    '"<description>"`. If just this task, note it and move on.',
    "Never write to `.eser/rules/` directly.",
    "",
    "## How to promote rules",
    "",
    "When a convention should be permanent, use the noskills CLI to register it:",
    "",
    `    ${commandPrefix} rule add "<description of the rule>"`,
    "",
    "This stores the rule in `.eser/rules/` and ensures it is synced to all",
    "coding tools on the next `noskills sync`. Never edit `.eser/rules/` directly.",
    "",
  ];

  return lines.join("\n");
};

const buildRules = (rules: readonly string[]): string => {
  const lines = [
    "---",
    "inclusion: always",
    "---",
    "",
    "# noskills Rules",
    "",
    "# Generated by noskills — do not edit manually",
    "",
    "## Active Rules",
    "",
  ];

  for (const rule of rules) {
    lines.push(`- ${rule}`);
  }

  lines.push("");

  return lines.join("\n");
};

// =============================================================================
// Hooks Config Generator
// =============================================================================

type KiroHook = {
  readonly _noskills?: boolean;
  readonly trigger: string;
  readonly condition?: { readonly toolNames: readonly string[] };
  readonly action: { readonly type: string; readonly command: string };
  readonly timeout: number;
};

type KiroHooksConfig = {
  hooks: KiroHook[];
};

const buildHooksConfig = (commandPrefix: string): KiroHooksConfig => ({
  hooks: [
    {
      _noskills: true,
      trigger: "Prompt Submit",
      action: {
        type: "Run Command",
        command: `${commandPrefix} invoke-hook session-start`,
      },
      timeout: 5000,
    },
    {
      _noskills: true,
      trigger: "Pre Tool Use",
      condition: {
        toolNames: ["write", "shell"],
      },
      action: {
        type: "Run Command",
        command: `${commandPrefix} invoke-hook pre-tool-use`,
      },
      timeout: 5000,
    },
    {
      _noskills: true,
      trigger: "Post Tool Use",
      condition: {
        toolNames: ["write"],
      },
      action: {
        type: "Run Command",
        command: `${commandPrefix} invoke-hook post-file-write`,
      },
      timeout: 3000,
    },
    {
      _noskills: true,
      trigger: "Post Tool Use",
      condition: {
        toolNames: ["shell"],
      },
      action: {
        type: "Run Command",
        command: `${commandPrefix} invoke-hook post-bash`,
      },
      timeout: 3000,
    },
    {
      _noskills: true,
      trigger: "Agent Stop",
      action: {
        type: "Run Command",
        command: `${commandPrefix} invoke-hook stop`,
      },
      timeout: 10000,
    },
  ],
});

// =============================================================================
// MCP Config Generator
// =============================================================================

type KiroMcpServerEntry = {
  readonly command: string;
  readonly args: readonly string[];
  readonly env: Record<string, string>;
  readonly autoApprove: readonly string[];
  readonly disabled: boolean;
};

type KiroMcpConfig = {
  mcpServers: Record<string, KiroMcpServerEntry>;
};

const buildMcpConfig = (commandPrefix: string): KiroMcpConfig => {
  const parts = commandPrefix.split(/\s+/);
  const command = parts[0] ?? "npx";
  const args = [...parts.slice(1), "mcp-serve"];

  return {
    mcpServers: {
      noskills: {
        command,
        args,
        env: {},
        autoApprove: ["noskills_next", "noskills_status"],
        disabled: false,
      },
    },
  };
};

// =============================================================================
// Agent Config Generators
// =============================================================================

type KiroAgent = {
  readonly name: string;
  readonly description: string;
  readonly tools: readonly string[];
  readonly allowedTools: readonly string[];
  readonly resources: readonly string[];
  readonly prompt: string;
};

const buildExecutorAgent = (commandPrefix: string): KiroAgent => ({
  name: "noskills-executor",
  description:
    "Executes a single noskills task. Follows spec behavioral rules and reports structured results.",
  tools: ["read", "write", "glob", "grep", "shell", "delegate"],
  allowedTools: ["read", "write", "glob", "grep", "shell", "delegate"],
  resources: [
    "file://.kiro/steering/noskills-protocol.md",
  ],
  prompt: [
    "You are executing a single task from a noskills spec.",
    "Your ONLY job is to complete the task described in the prompt.",
    "Follow all behavioral rules provided in the prompt.",
    "Do NOT start new tasks, explore unrelated code, or make architectural decisions.",
    "If the task is too vague to execute, say so immediately.",
    "",
    "## Self-Verification",
    "After completing the task, you MUST verify your own work before reporting:",
    "1. Run type check: `deno check` on all modified files",
    "2. Run test suite: `deno test` on the relevant test files",
    "3. If type check or tests fail, fix the issues before reporting",
    "",
    "## Reporting",
    "When finished, provide a structured JSON summary:",
    "```json",
    '{"completed": ["<item IDs done>"], "remaining": ["<item IDs not done>"], "blocked": ["<item IDs needing decisions>"], "filesModified": ["<paths>"], "verification": {"typeCheck": "pass|fail", "tests": "pass|fail (N passed, M failed)"}}',
    "```",
    "",
    "Do NOT return raw test output — summarize it in the verification field.",
    `The orchestrator will submit this to \`${commandPrefix} next --answer\` on your behalf.`,
  ].join("\n"),
});

const buildVerifierAgent = (): KiroAgent => ({
  name: "noskills-verifier",
  description:
    "Independently verifies completed task work. Read-only. Never sees the executor's context.",
  tools: ["read", "glob", "grep", "shell", "use_subagent"],
  allowedTools: ["read", "glob", "grep", "shell"],
  resources: [
    "file://.kiro/steering/noskills-protocol.md",
  ],
  prompt: [
    "You are verifying another agent's work. You have NO context about how it was done.",
    "Read the changed files. Run the test suite. Check each acceptance criterion independently.",
    "",
    "For each acceptance criterion:",
    "- PASS: with evidence — show the grep result, the test output, or the file content that proves it",
    "- FAIL: with specific reason — what's missing, what's wrong, what doesn't match",
    "",
    "Be skeptical. Don't assume anything works — verify it yourself.",
    "You CANNOT edit files. Read-only access only.",
    "",
    "## Verification Steps",
    "1. Read each modified file and verify the changes are correct",
    "2. Run type check: `deno check` on modified files",
    "3. Run tests: `deno test` on relevant test files",
    "4. Check each acceptance criterion against actual file contents",
    "",
    "## Report Format",
    "When finished, provide a structured JSON summary:",
    "```json",
    '{"results": [{"id": "ac-1", "status": "PASS", "evidence": "..."}, {"id": "ac-2", "status": "FAIL", "reason": "..."}]}',
    "```",
    "",
    "The orchestrator will use this report for the noskills status report.",
  ].join("\n"),
});

// =============================================================================
// File Helpers
// =============================================================================

const fileExists = async (path: string): Promise<boolean> => {
  try {
    await crossRuntime.runtime.fs.stat(path);
    return true;
  } catch {
    return false;
  }
};

// =============================================================================
// Spec Parsing & Projection
// =============================================================================

type ParsedSpec = {
  readonly title: string;
  readonly concerns: string;
  readonly discoveryAnswers: string;
  readonly contributorGuide: string;
  readonly publicApi: string;
  readonly outOfScope: string;
  readonly tasks: string;
  readonly verification: string;
};

const parseSpecMd = (content: string): ParsedSpec => {
  // Extract title from first H1
  const titleMatch = content.match(/^# Spec:\s*(.+)$/m);
  const title = titleMatch?.[1]?.trim() ?? "Untitled";

  // Split on ## headings and build a section map
  const sections = new Map<string, string>();
  const parts = content.split(/^## /m);

  for (const part of parts) {
    const newlineIdx = part.indexOf("\n");

    if (newlineIdx === -1) {
      continue;
    }

    const heading = part.slice(0, newlineIdx).trim().toLowerCase();
    const body = part.slice(newlineIdx + 1).trim();
    sections.set(heading, body);
  }

  // Match section headings (case-insensitive, prefix match)
  const findSection = (prefix: string): string => {
    for (const [key, value] of sections) {
      if (key.startsWith(prefix.toLowerCase())) {
        return value;
      }
    }

    return "";
  };

  return {
    title,
    concerns: findSection("concerns"),
    discoveryAnswers: findSection("discovery answers"),
    contributorGuide: findSection("contributor guide"),
    publicApi: findSection("public api"),
    outOfScope: findSection("out of scope"),
    tasks: findSection("tasks"),
    verification: findSection("verification"),
  };
};

const buildRequirementsMd = (spec: ParsedSpec): string => {
  const lines = [
    `# Feature: ${spec.title}`,
    "",
    "## Overview",
    "",
    spec.discoveryAnswers || "(no discovery answers yet)",
    "",
    "## Requirements",
    "",
  ];

  // Extract requirements from discovery answers — use subsection headings as items
  const reqLines = spec.discoveryAnswers.split("\n").filter((l) =>
    l.startsWith("### ")
  );

  if (reqLines.length > 0) {
    for (const line of reqLines) {
      lines.push(`- ${line.replace(/^###\s*/, "")}`);
    }
  } else if (spec.discoveryAnswers) {
    lines.push("- See overview for details");
  } else {
    lines.push("- (none yet)");
  }

  lines.push("", "## Acceptance Criteria", "");

  // Map verification items to acceptance criteria
  if (spec.verification) {
    const verLines = spec.verification.split("\n").filter((l) => l.trim());
    for (const line of verLines) {
      const trimmed = line.replace(/^[-*]\s*/, "").trim();

      if (trimmed) {
        lines.push(`- [ ] ${trimmed}`);
      }
    }
  } else {
    lines.push("- [ ] (none yet)");
  }

  lines.push("", "## Out of Scope", "");
  lines.push(spec.outOfScope || "(nothing listed)");
  lines.push("");

  return lines.join("\n");
};

const buildDesignMd = (spec: ParsedSpec): string => {
  const lines = [
    `# Design: ${spec.title}`,
    "",
    "## Architecture",
    "",
  ];

  // Extract architecture info from discovery answers
  if (spec.discoveryAnswers) {
    lines.push(spec.discoveryAnswers);
  } else {
    lines.push("(no architecture decisions yet)");
  }

  lines.push("", "## Concerns", "");

  if (spec.concerns) {
    lines.push(spec.concerns);
  } else {
    lines.push("(no active concerns)");
  }

  lines.push("", "## Decisions", "");

  // Contributor guide and public API inform design decisions
  if (spec.contributorGuide || spec.publicApi) {
    if (spec.contributorGuide) {
      lines.push("### Contributor Guide", "", spec.contributorGuide, "");
    }

    if (spec.publicApi) {
      lines.push("### Public API Surface", "", spec.publicApi, "");
    }
  } else {
    lines.push("(no decisions yet)");
  }

  lines.push("");

  return lines.join("\n");
};

const buildTasksMd = (spec: ParsedSpec): string => {
  const lines = [
    `# Tasks: ${spec.title}`,
    "",
  ];

  if (spec.tasks) {
    lines.push(spec.tasks);
  } else {
    lines.push("(no tasks yet)");
  }

  lines.push("");

  return lines.join("\n");
};

// =============================================================================
// Adapter
// =============================================================================

export const kiroAdapter: adapter.ToolAdapter = {
  id: "kiro",

  capabilities: {
    rules: true,
    hooks: true,
    agents: true,
    specs: true,
    mcp: true,
    interaction: {
      hasAskUserTool: false,
      optionPresentation: "prose",
      hasSubAgentDelegation: true,
      subAgentMethod: "delegation",
    },
  },

  async syncRules(
    ctx: adapter.SyncContext,
    options?: adapter.SyncOptions,
  ): Promise<void> {
    const steeringDir = `${ctx.root}/${STEERING_DIR}`;
    await crossRuntime.runtime.fs.mkdir(steeringDir, { recursive: true });

    // 1. Protocol — always generated
    await crossRuntime.runtime.fs.writeTextFile(
      `${steeringDir}/${PROTOCOL_FILE}`,
      buildProtocol(ctx.commandPrefix, options),
    );

    // 2. Coaching — always generated
    await crossRuntime.runtime.fs.writeTextFile(
      `${steeringDir}/${COACHING_FILE}`,
      buildCoaching(ctx.commandPrefix),
    );

    // 3. Rules — only if rules exist; clean up stale file otherwise
    if (ctx.rules.length > 0) {
      await crossRuntime.runtime.fs.writeTextFile(
        `${steeringDir}/${RULES_FILE}`,
        buildRules(ctx.rules),
      );
    } else if (await fileExists(`${steeringDir}/${RULES_FILE}`)) {
      await crossRuntime.runtime.fs.remove(`${steeringDir}/${RULES_FILE}`);
    }

    // 4. Clean up legacy conventions.md from old single-file format
    if (await fileExists(`${steeringDir}/${LEGACY_FILE}`)) {
      await crossRuntime.runtime.fs.remove(`${steeringDir}/${LEGACY_FILE}`);
    }
  },

  async syncHooks(
    ctx: adapter.SyncContext,
    _options?: adapter.SyncOptions,
  ): Promise<void> {
    const hooksDir = `${ctx.root}/${HOOKS_DIR}`;
    const hooksPath = `${hooksDir}/${HOOKS_FILE}`;

    await crossRuntime.runtime.fs.mkdir(hooksDir, { recursive: true });

    // Read existing hooks config (preserve non-noskills hooks)
    let existingHooks: KiroHook[] = [];
    try {
      const content = await crossRuntime.runtime.fs.readTextFile(hooksPath);
      const parsed = JSON.parse(content) as KiroHooksConfig;
      if (Array.isArray(parsed.hooks)) {
        existingHooks = parsed.hooks;
      }
    } catch {
      // File doesn't exist yet
    }

    // Filter out previous noskills-managed hooks, keep user hooks
    const userHooks = existingHooks.filter(
      (h) => !(h as { _noskills?: boolean })._noskills,
    );

    // Build fresh noskills hooks and merge
    const noskillsConfig = buildHooksConfig(ctx.commandPrefix);
    const merged: KiroHooksConfig = {
      hooks: [...userHooks, ...noskillsConfig.hooks],
    };

    await crossRuntime.runtime.fs.writeTextFile(
      hooksPath,
      JSON.stringify(merged, null, 2) + "\n",
    );
  },

  async syncAgents(
    ctx: adapter.SyncContext,
    _options?: adapter.SyncOptions,
  ): Promise<void> {
    const agentsDir = `${ctx.root}/${AGENTS_DIR}`;
    await crossRuntime.runtime.fs.mkdir(agentsDir, { recursive: true });

    // 1. Executor agent — write tools + delegation
    const executor = buildExecutorAgent(ctx.commandPrefix);
    await crossRuntime.runtime.fs.writeTextFile(
      `${agentsDir}/${EXECUTOR_FILE}`,
      JSON.stringify(executor, null, 2) + "\n",
    );

    // 2. Verifier agent — read-only tools + sub-agent coordination
    const verifier = buildVerifierAgent();
    await crossRuntime.runtime.fs.writeTextFile(
      `${agentsDir}/${VERIFIER_FILE}`,
      JSON.stringify(verifier, null, 2) + "\n",
    );
  },

  async syncSpecs(
    ctx: adapter.SyncContext,
    specPath: string,
  ): Promise<void> {
    // Read the noskills spec.md
    let content: string;

    try {
      content = await crossRuntime.runtime.fs.readTextFile(specPath);
    } catch {
      // File doesn't exist — skip gracefully
      return;
    }

    if (content.trim() === "") {
      return;
    }

    // Derive spec name from the path: .eser/specs/<spec-name>/spec.md
    const segments = specPath.split("/");
    const specName = segments[segments.length - 2] ?? "unknown";

    // Parse the noskills spec
    const parsed = parseSpecMd(content);

    // Write Kiro's three-file format
    const specDir = `${ctx.root}/${SPECS_DIR}/${specName}`;
    await crossRuntime.runtime.fs.mkdir(specDir, { recursive: true });

    await crossRuntime.runtime.fs.writeTextFile(
      `${specDir}/requirements.md`,
      buildRequirementsMd(parsed),
    );

    await crossRuntime.runtime.fs.writeTextFile(
      `${specDir}/design.md`,
      buildDesignMd(parsed),
    );

    await crossRuntime.runtime.fs.writeTextFile(
      `${specDir}/tasks.md`,
      buildTasksMd(parsed),
    );
  },

  async syncMcp(
    ctx: adapter.SyncContext,
  ): Promise<void> {
    const settingsDir = `${ctx.root}/${HOOKS_DIR}`;
    const mcpPath = `${settingsDir}/${MCP_FILE}`;

    await crossRuntime.runtime.fs.mkdir(settingsDir, { recursive: true });

    // Read existing MCP config (preserve non-noskills servers)
    let existing: KiroMcpConfig = { mcpServers: {} };
    try {
      const content = await crossRuntime.runtime.fs.readTextFile(mcpPath);
      const parsed = JSON.parse(content) as KiroMcpConfig;
      if (parsed.mcpServers !== undefined && parsed.mcpServers !== null) {
        existing = parsed;
      }
    } catch {
      // File doesn't exist yet
    }

    // Build fresh noskills MCP entry and merge
    const noskillsConfig = buildMcpConfig(ctx.commandPrefix);
    const merged: KiroMcpConfig = {
      ...existing,
      mcpServers: {
        ...existing.mcpServers,
        ...noskillsConfig.mcpServers,
      },
    };

    await crossRuntime.runtime.fs.writeTextFile(
      mcpPath,
      JSON.stringify(merged, null, 2) + "\n",
    );
  },
};
