// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * OpenCode adapter — implements ToolAdapter for OpenCode, generating AGENTS.md,
 * plugin hooks, agent definitions, skill files, and MCP configuration.
 *
 * @module
 */

import type * as adapter from "../adapter.ts";
import * as agentsMd from "./shared/agents-md.ts";
import * as crossRuntime from "@eserstack/standards/cross-runtime";

// =============================================================================
// File Paths
// =============================================================================

const PLUGINS_DIR = ".opencode/plugins";
const AGENTS_DIR = ".opencode/agents";
const SKILLS_DIR = ".opencode/skills";
const CONFIG_FILE = "opencode.json";

// =============================================================================
// Hooks Content Generator (Plugin)
// =============================================================================

const buildPluginContent = (commandPrefix: string): string => {
  const lines = [
    "// Generated by noskills — do not edit manually",
    'import { execSync } from "node:child_process";',
    "",
    "const run = (event: string): void => {",
    "  try {",
    `    execSync(\`${commandPrefix} invoke-hook \${event}\`, {`,
    '      stdio: "inherit",',
    "      timeout: 10000,",
    "    });",
    "  } catch {",
    "    // Hook failure should not block the session",
    "  }",
    "};",
    "",
    "export default async () => ({",
    '  "session.created": async () => {',
    '    run("session-start");',
    "  },",
    '  "tool.execute.before": async (params: { toolName: string }) => {',
    '    if (["write", "shell"].includes(params.toolName)) {',
    '      run("pre-tool-use");',
    "    }",
    "  },",
    '  "tool.execute.after": async (params: { toolName: string }) => {',
    '    if (params.toolName === "write") {',
    '      run("post-file-write");',
    '    } else if (params.toolName === "shell") {',
    '      run("post-bash");',
    "    }",
    "  },",
    '  "session.deleted": async () => {',
    '    run("stop");',
    "  },",
    "});",
    "",
  ];

  return lines.join("\n");
};

// =============================================================================
// Agent Content Generators
// =============================================================================

const buildExecutorAgentMd = (commandPrefix: string): string => {
  const lines = [
    "---",
    "name: noskills-executor",
    'description: "Executes a single noskills task. Follows spec behavioral rules and reports structured results."',
    "tools: read, write, glob, grep, shell, delegate",
    "---",
    "",
    "You are executing a single task from a noskills spec.",
    "Your ONLY job is to complete the task described in the prompt.",
    "Follow all behavioral rules provided in the prompt.",
    "Do NOT start new tasks, explore unrelated code, or make architectural decisions.",
    "If the task is too vague to execute, say so immediately.",
    "",
    "## Self-Verification",
    "After completing the task, you MUST verify your own work before reporting:",
    "1. Run type check: `deno check` on all modified files",
    "2. Run test suite: `deno test` on the relevant test files",
    "3. If type check or tests fail, fix the issues before reporting",
    "",
    "## Reporting",
    "When finished, provide a structured JSON summary:",
    "```json",
    '{"completed": ["<item IDs done>"], "remaining": ["<item IDs not done>"], "blocked": ["<item IDs needing decisions>"], "filesModified": ["<paths>"], "verification": {"typeCheck": "pass|fail", "tests": "pass|fail (N passed, M failed)"}}',
    "```",
    "",
    "Do NOT return raw test output — summarize it in the verification field.",
    `The orchestrator will submit this to \`${commandPrefix} next --answer\` on your behalf.`,
    "",
  ];

  return lines.join("\n");
};

const buildVerifierAgentMd = (): string => {
  const lines = [
    "---",
    "name: noskills-verifier",
    'description: "Independently verifies completed task work. Read-only. Never sees the executor\'s context."',
    "tools: read, glob, grep, shell",
    "---",
    "",
    "You are verifying another agent's work. You have NO context about how it was done.",
    "Read the changed files. Run the test suite. Check each acceptance criterion independently.",
    "",
    "For each acceptance criterion:",
    "- PASS: with evidence — show the grep result, the test output, or the file content that proves it",
    "- FAIL: with specific reason — what's missing, what's wrong, what doesn't match",
    "",
    "Be skeptical. Don't assume anything works — verify it yourself.",
    "You CANNOT edit files. Read-only access only.",
    "",
    "## Verification Steps",
    "1. Read each modified file and verify the changes are correct",
    "2. Run type check: `deno check` on modified files",
    "3. Run tests: `deno test` on relevant test files",
    "4. Check each acceptance criterion against actual file contents",
    "",
    "## Report Format",
    "When finished, provide a structured JSON summary:",
    "```json",
    '{"results": [{"id": "ac-1", "status": "PASS", "evidence": "..."}, {"id": "ac-2", "status": "FAIL", "reason": "..."}]}',
    "```",
    "",
    "The orchestrator will use this report for the noskills status report.",
    "",
  ];

  return lines.join("\n");
};

// =============================================================================
// Spec Parsing & Projection
// =============================================================================

type ParsedSpec = {
  readonly title: string;
  readonly concerns: string;
  readonly discoveryAnswers: string;
  readonly contributorGuide: string;
  readonly publicApi: string;
  readonly outOfScope: string;
  readonly tasks: string;
  readonly verification: string;
};

const parseSpecMd = (content: string): ParsedSpec => {
  // Extract title from first H1
  const titleMatch = content.match(/^# Spec:\s*(.+)$/m);
  const title = titleMatch?.[1]?.trim() ?? "Untitled";

  // Split on ## headings and build a section map
  const sections = new Map<string, string>();
  const parts = content.split(/^## /m);

  for (const part of parts) {
    const newlineIdx = part.indexOf("\n");

    if (newlineIdx === -1) {
      continue;
    }

    const heading = part.slice(0, newlineIdx).trim().toLowerCase();
    const body = part.slice(newlineIdx + 1).trim();
    sections.set(heading, body);
  }

  // Match section headings (case-insensitive, prefix match)
  const findSection = (prefix: string): string => {
    for (const [key, value] of sections) {
      if (key.startsWith(prefix.toLowerCase())) {
        return value;
      }
    }

    return "";
  };

  return {
    title,
    concerns: findSection("concerns"),
    discoveryAnswers: findSection("discovery answers"),
    contributorGuide: findSection("contributor guide"),
    publicApi: findSection("public api"),
    outOfScope: findSection("out of scope"),
    tasks: findSection("tasks"),
    verification: findSection("verification"),
  };
};

const buildSkillMd = (spec: ParsedSpec): string => {
  const lines = [
    "---",
    `name: ${spec.title}`,
    `description: "noskills spec: ${spec.title}"`,
    "---",
    "",
    `# ${spec.title}`,
    "",
  ];

  if (spec.discoveryAnswers) {
    lines.push("## Overview", "", spec.discoveryAnswers, "");
  }

  if (spec.concerns) {
    lines.push("## Concerns", "", spec.concerns, "");
  }

  if (spec.contributorGuide) {
    lines.push("## Contributor Guide", "", spec.contributorGuide, "");
  }

  if (spec.publicApi) {
    lines.push("## Public API", "", spec.publicApi, "");
  }

  if (spec.outOfScope) {
    lines.push("## Out of Scope", "", spec.outOfScope, "");
  }

  if (spec.tasks) {
    lines.push("## Tasks", "", spec.tasks, "");
  }

  if (spec.verification) {
    lines.push("## Verification", "", spec.verification, "");
  }

  return lines.join("\n");
};

// =============================================================================
// MCP Config Types
// =============================================================================

type OpenCodeMcpEntry = {
  readonly type: "local";
  readonly command: string;
  readonly args: readonly string[];
  readonly env?: Record<string, string>;
};

type OpenCodeConfig = {
  mcp?: Record<string, OpenCodeMcpEntry>;
  [key: string]: unknown;
};

// =============================================================================
// File Helpers
// =============================================================================

const fileExists = async (path: string): Promise<boolean> => {
  try {
    await crossRuntime.runtime.fs.stat(path);
    return true;
  } catch {
    return false;
  }
};

// =============================================================================
// Adapter
// =============================================================================

export const opencodeAdapter: adapter.ToolAdapter = {
  id: "opencode",

  capabilities: {
    rules: true,
    hooks: true,
    agents: true,
    specs: true,
    mcp: true,
    interaction: {
      hasAskUserTool: false,
      optionPresentation: "prose",
      hasSubAgentDelegation: true,
      subAgentMethod: "delegation",
    },
  },

  async syncRules(
    ctx: adapter.SyncContext,
    options?: adapter.SyncOptions,
  ): Promise<void> {
    await agentsMd.syncAgentsMd(ctx, options);
  },

  async syncHooks(
    ctx: adapter.SyncContext,
    _options?: adapter.SyncOptions,
  ): Promise<void> {
    const pluginsDir = `${ctx.root}/${PLUGINS_DIR}`;
    await crossRuntime.runtime.fs.mkdir(pluginsDir, { recursive: true });

    await crossRuntime.runtime.fs.writeTextFile(
      `${pluginsDir}/noskills.ts`,
      buildPluginContent(ctx.commandPrefix),
    );
  },

  async syncAgents(
    ctx: adapter.SyncContext,
    _options?: adapter.SyncOptions,
  ): Promise<void> {
    const agentsDir = `${ctx.root}/${AGENTS_DIR}`;
    await crossRuntime.runtime.fs.mkdir(agentsDir, { recursive: true });

    // 1. Executor agent
    await crossRuntime.runtime.fs.writeTextFile(
      `${agentsDir}/noskills-executor.md`,
      buildExecutorAgentMd(ctx.commandPrefix),
    );

    // 2. Verifier agent (read-only)
    await crossRuntime.runtime.fs.writeTextFile(
      `${agentsDir}/noskills-verifier.md`,
      buildVerifierAgentMd(),
    );
  },

  async syncSpecs(
    ctx: adapter.SyncContext,
    specPath: string,
  ): Promise<void> {
    // Read the noskills spec.md
    let content: string;

    try {
      content = await crossRuntime.runtime.fs.readTextFile(specPath);
    } catch {
      // File doesn't exist — skip gracefully
      return;
    }

    if (content.trim() === "") {
      return;
    }

    // Derive spec name from the path: .eser/specs/<spec-name>/spec.md
    const segments = specPath.split("/");
    const specName = segments[segments.length - 2] ?? "unknown";

    // Parse the noskills spec
    const parsed = parseSpecMd(content);

    // Write OpenCode skill file
    const skillsDir = `${ctx.root}/${SKILLS_DIR}`;
    await crossRuntime.runtime.fs.mkdir(skillsDir, { recursive: true });

    await crossRuntime.runtime.fs.writeTextFile(
      `${skillsDir}/${specName}.md`,
      buildSkillMd(parsed),
    );
  },

  async syncMcp(
    ctx: adapter.SyncContext,
  ): Promise<void> {
    const configPath = `${ctx.root}/${CONFIG_FILE}`;

    // Read existing config (preserve non-noskills config)
    let existing: OpenCodeConfig = {};
    if (await fileExists(configPath)) {
      try {
        const content = await crossRuntime.runtime.fs.readTextFile(configPath);
        const parsed = JSON.parse(content) as OpenCodeConfig;
        existing = parsed;
      } catch {
        // Malformed JSON — start fresh
      }
    }

    // Build noskills MCP entry
    const parts = ctx.commandPrefix.split(/\s+/);
    const command = parts[0] ?? "npx";
    const args = [...parts.slice(1), "mcp-serve"];

    // Merge
    const merged: OpenCodeConfig = {
      ...existing,
      mcp: {
        ...existing.mcp,
        noskills: {
          type: "local",
          command,
          args,
        },
      },
    };

    await crossRuntime.runtime.fs.writeTextFile(
      configPath,
      JSON.stringify(merged, null, 2) + "\n",
    );
  },
};
