// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * `noskills spec <name> plan-export` — Export spec state to .claude/plan.md.
 *
 * Generates a Claude Code-compatible plan.md from the current spec, including
 * tasks (with completion checkboxes), ACs, out-of-scope, and verification.
 *
 * @module
 */

import * as results from "@eserstack/primitives/results";
import type * as shellArgs from "@eserstack/shell/args";
import * as persistence from "../state/persistence.ts";
import * as specParser from "../spec/parser.ts";
import { runtime } from "@eserstack/standards/cross-runtime";

const ALLOWED_PHASES = new Set(["SPEC_PROPOSAL", "SPEC_APPROVED", "EXECUTING"]);

export const main = async (
  args?: readonly string[],
): Promise<shellArgs.CliResult<void>> => {
  const { root } = await persistence.resolveProjectRoot();
  const specResult = persistence.requireSpecFlag(args);
  if (!specResult.ok) {
    console.error(specResult.error);
    return results.fail({ exitCode: 1 });
  }

  const specName = specResult.spec;
  let state;
  try {
    state = await persistence.resolveState(root, specName);
  } catch (err: unknown) {
    console.error(err instanceof Error ? err.message : String(err));
    return results.fail({ exitCode: 1 });
  }

  if (!ALLOWED_PHASES.has(state.phase)) {
    console.error(
      `Spec must be in SPEC_PROPOSAL, SPEC_APPROVED, or EXECUTING to export a plan (current: ${state.phase}).`,
    );
    return results.fail({ exitCode: 1 });
  }

  // Parse spec.md for tasks
  const parsed = await specParser.parseSpec(root, specName);
  const completedSet = new Set(state.execution.completedTasks);

  // Build content sections
  const lines: string[] = [];

  lines.push(`# Plan: ${specName}`);
  lines.push(
    `Generated by noskills ${new Date().toISOString()} from spec/${specName}`,
  );
  lines.push("");

  // Summary
  lines.push("## Summary");
  lines.push(state.specDescription?.trim() ?? "(not yet defined)");
  lines.push("");

  // Tasks
  lines.push("## Tasks");
  if (parsed !== null && parsed.tasks.length > 0) {
    for (const task of parsed.tasks) {
      const check = completedSet.has(task.id) ? "x" : " ";
      lines.push(`- [${check}] ${task.title}`);
    }
  } else {
    lines.push("(not yet defined)");
  }
  lines.push("");

  // Acceptance Criteria
  lines.push("## Acceptance Criteria");
  const customACs = state.customACs ?? [];
  if (customACs.length > 0) {
    for (const ac of customACs) {
      lines.push(`- ${ac.text}`);
    }
  } else {
    lines.push("(not yet defined)");
  }
  lines.push("");

  // Out of Scope
  lines.push("## Out of Scope");
  const scopeAnswer = state.discovery.answers.find(
    (a) => a.questionId === "scope_boundary",
  );
  if (scopeAnswer !== undefined && scopeAnswer.answer.trim().length > 0) {
    const scopeLines = scopeAnswer.answer
      .split("\n")
      .map((l) => l.trim())
      .filter((l) => l.length > 0);
    for (const l of scopeLines) {
      lines.push(`- ${l}`);
    }
  } else {
    lines.push("(not yet defined)");
  }
  lines.push("");

  // Verification
  lines.push("## Verification");
  const verifyAnswer = state.discovery.answers.find(
    (a) => a.questionId === "verification",
  );
  if (verifyAnswer !== undefined && verifyAnswer.answer.trim().length > 0) {
    lines.push(verifyAnswer.answer.trim());
  } else {
    lines.push("(not yet defined)");
  }
  lines.push("");

  const content = lines.join("\n");
  const planPath = `${root}/.claude/plan.md`;

  try {
    await runtime.fs.mkdir(`${root}/.claude`, { recursive: true });
    await runtime.fs.writeTextFile(planPath, content);
    console.log(`Written: ${planPath}`);
  } catch (err: unknown) {
    console.error(
      `Failed to write plan.md: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
    return results.fail({ exitCode: 1 });
  }

  return results.ok(undefined);
};
