// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * GitHub Copilot sync — generates .github/copilot-instructions.md.
 *
 * @module
 */

import { runtime } from "@eser/standards/cross-runtime";

export const sync = async (
  root: string,
  rules: readonly string[],
): Promise<void> => {
  const lines = [
    "# Generated by noskills — do not edit manually",
    "",
    "## Orchestration",
    "",
    "This project uses noskills for AI orchestration.",
    "Run `npx eser noskills next` at every step.",
    "",
  ];

  if (rules.length > 0) {
    lines.push("## Rules", "");
    for (const rule of rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
  }

  await runtime.fs.mkdir(`${root}/.github`, {
    recursive: true,
  });
  await runtime.fs.writeTextFile(
    `${root}/.github/copilot-instructions.md`,
    lines.join("\n"),
  );
};
