// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Kiro sync — generates .kiro/steering/conventions.md.
 *
 * @module
 */

import { runtime } from "@eser/standards/cross-runtime";

export const sync = async (
  root: string,
  rules: readonly string[],
  commandPrefix = "npx eser noskills",
): Promise<void> => {
  const lines = [
    "# Generated by noskills — do not edit manually",
    "",
    "## noskills orchestrator",
    "",
    "This project uses noskills for state-driven orchestration.",
    "Do NOT read `.eser/specs/` or `.eser/rules/` directly. noskills gives you what you need.",
    "",
    `Run \`${commandPrefix} next\` to get your current instruction.`,
    `Submit results with \`${commandPrefix} next --answer="..."\``,
    "",
    "## When to call noskills next",
    "",
    "1. At the START of every conversation",
    "2. BEFORE creating or modifying any file",
    "3. AFTER completing a logical unit of work",
    "4. When you encounter a DECISION that affects architecture",
    "5. When you are UNSURE what to do next",
    "",
    "NEVER proceed with implementation without checking noskills first.",
    "NEVER suggest bypassing or skipping noskills. Discovery is not overhead.",
    "NEVER ask permission to run the next noskills command. After spec new → run next. After approve → run next. Each step has one next step. Just run it.",
    "",
  ];

  if (rules.length > 0) {
    lines.push("## Rules", "");
    for (const rule of rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
  }

  await runtime.fs.mkdir(`${root}/.kiro/steering`, {
    recursive: true,
  });
  await runtime.fs.writeTextFile(
    `${root}/.kiro/steering/conventions.md`,
    lines.join("\n"),
  );
};
