// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Kiro sync — generates .kiro/steering/conventions.md.
 *
 * @module
 */

export const sync = async (
  root: string,
  rules: readonly string[],
): Promise<void> => {
  const lines = [
    "# Generated by noskills — do not edit manually",
    "",
    "## Orchestration",
    "",
    "This project uses noskills for AI orchestration.",
    "Run `npx eser noskills next` at every step.",
    "",
  ];

  if (rules.length > 0) {
    lines.push("## Rules", "");
    for (const rule of rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
  }

  await Deno.mkdir(`${root}/.kiro/steering`, { recursive: true });
  await Deno.writeTextFile(
    `${root}/.kiro/steering/conventions.md`,
    lines.join("\n"),
  );
};
