// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

// This file contains code from deno fresh (https://github.com/denoland/fresh),
// which is a web framework, licensed under the MIT license.

// Copyright (c) 2023 Eser Ozvataf and other contributors
// Copyright (c) 2021-2023 Luca Casonato

import { runtime, toPosix } from "@eserstack/standards/cross-runtime";
import * as logger from "@eserstack/logging/logger";
import * as validatorIdentifier from "./validator-identifier/mod.ts";
import * as formatter from "./formatter.ts";
import * as collector from "./collector.ts";
import { ensureLib, getLib } from "./ffi-client.ts";

const IMPORT_PREFIX = "$$";
const PLACEHOLDER_PREFIX = `##!!//__`;
const PLACEHOLDER_SUFFIX = "__//!!##";

/**
 * Convert a file path to an import specifier.
 * Normalizes to POSIX format and ensures ./ prefix for relative imports.
 */
const toImportSpecifier = (file: string) => {
  const specifier = toPosix(runtime.path.normalize(file));

  if (!specifier.startsWith(".")) {
    return `./${specifier}`;
  }

  return specifier;
};

// Create a valid JS identifier out of the project relative specifier.
export const specifierToIdentifier = (
  specifier: string,
  used: Set<string>,
): string => {
  const lib = getLib();

  if (lib !== null) {
    const raw = lib.symbols.EserAjanCollectorSpecifierToIdentifier(
      JSON.stringify({ specifier, used: [...used] }),
    );
    const result = JSON.parse(raw) as { identifier: string; error?: string };
    if (!result.error) {
      used.add(result.identifier);
      return result.identifier;
    }
  }

  // Fallback: TS implementation
  const ext = runtime.path.extname(specifier);
  let spec = ext ? specifier.slice(0, -ext.length) : specifier;

  let ident = "";
  for (let i = 0; i < spec.length; i++) {
    const char = spec.charCodeAt(i);
    if (i === 0 && !validatorIdentifier.isIdentifierStart(char)) {
      ident += "_";
      if (validatorIdentifier.isIdentifierChar(char)) {
        ident += spec[i];
      }
    } else if (!validatorIdentifier.isIdentifierChar(char)) {
      if (ident[ident.length - 1] !== "_") {
        ident += "_";
      }
    } else if (ident[ident.length - 1] !== "_" || spec[i] !== "_") {
      ident += spec[i];
    }
  }

  if (used.has(ident)) {
    let check = ident;
    let i = 1;

    while (used.has(check)) {
      check = `${ident}_${i++}`;
    }

    ident = check;
  }

  used.add(ident);

  return ident;
};

const getSortFn = () => {
  const naturalCollator = new Intl.Collator(undefined, { numeric: true });
  return naturalCollator.compare;
};

const placeholder = (text: string) => {
  return `${PLACEHOLDER_PREFIX}${text}${PLACEHOLDER_SUFFIX}`;
};

export const writeManifestToString = async (
  collection: Array<[string, Array<[string, unknown]>]>,
): Promise<string> => {
  await ensureLib();
  const lib = getLib();

  if (lib !== null) {
    const entries = collection.map(([relPath, exports]) => ({
      relPath,
      exports: exports.map(([name]) => name),
    }));
    const raw = lib.symbols.EserAjanCollectorGenerateManifest(
      JSON.stringify({ entries }),
    );
    const result = JSON.parse(raw) as { source: string; error?: string };
    if (!result.error) {
      return result.source;
    }
  }

  // Fallback: TS manifest generation
  const sortFn = getSortFn();
  const used = new Set<string>();
  const imports: Array<string> = [];
  const manifest = {
    exports: [] as Array<string>,
  };

  for (const [file, exports] of collection) {
    const specifier = toImportSpecifier(file);
    const identifier = specifierToIdentifier(file, used);

    imports.push(
      `import * as ${IMPORT_PREFIX}${identifier} from "${specifier}";`,
    );

    const ref = (target: unknown) => {
      const name = (target as { name: string }).name;
      return placeholder(`${IMPORT_PREFIX}${identifier}.${name}`);
    };

    for (const [, moduleFn] of exports) {
      manifest.exports.push(ref(moduleFn));
    }
  }

  imports.sort(sortFn);
  const importsSerialized = imports.join("\n");

  manifest.exports.sort(sortFn);
  const manifestSerialized = JSON.stringify(manifest, null, 2)
    .replaceAll(`"${PLACEHOLDER_PREFIX}`, "")
    .replaceAll(`${PLACEHOLDER_SUFFIX}"`, "");

  const output =
    `// This file is generated by @eserstack/collector. Your changes might be overwritten.

${importsSerialized}

export const manifest = ${manifestSerialized};
`;

  return formatter.format(output);
};

export const buildManifest = async (
  target: WritableStream,
  options: collector.CollectExportsOptions,
): Promise<void> => {
  const collection = await collector.collectExports(options);
  const manifestStr = await writeManifestToString(collection);

  const outputWriter = target.getWriter();
  try {
    await outputWriter.ready;
    const encoded = new TextEncoder().encode(manifestStr);
    await outputWriter.write(encoded);
  } finally {
    outputWriter.releaseLock();
  }

  const exportModules = Object.values(collection);
  const exportCount = exportModules.reduce((acc, [, moduleFns]) => {
    acc += moduleFns.length;
    return acc;
  }, 0);

  logger.current.info(
    `The manifest file has been generated for ${exportCount} exports in ${exportModules.length} modules.`,
  );
};

export const buildManifestFile = async (
  filepath: string,
  options: collector.CollectExportsOptions,
): Promise<void> => {
  const collection = await collector.collectExports(options);
  const manifestStr = await writeManifestToString(collection);

  await runtime.fs.writeTextFile(filepath, manifestStr);

  const exportModules = Object.values(collection);
  const exportCount = exportModules.reduce((acc, [, moduleFns]) => {
    acc += moduleFns.length;
    return acc;
  }, 0);

  logger.current.info(
    `The manifest file has been generated for ${exportCount} exports in ${exportModules.length} modules.`,
  );
};
