// This file is generated by @eser/collector. Your changes might be overwritten.

import * as $$pkg_routes_demo from "./pkg/routes/demo.tsx";

export const manifest = {
  "exports": [
    $$pkg_routes_demo.limeModule,
  ],
};
