// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Windsurf sync — generates .windsurfrules.
 *
 * @module
 */

import { runtime } from "@eserstack/standards/cross-runtime";

export const sync = async (
  root: string,
  rules: readonly string[],
  commandPrefix = "npx eser noskills",
): Promise<void> => {
  const lines = [
    "# Generated by noskills — do not edit manually",
    "",
    "## noskills orchestrator",
    "",
    "This project uses noskills for state-driven orchestration.",
    "Do NOT read `.eser/specs/` or `.eser/rules/` directly. noskills gives you what you need.",
    "",
    `Run \`${commandPrefix} next\` to get your current instruction.`,
    `Submit results with \`${commandPrefix} next --answer="..."\``,
    "",
    "## Why noskills calls matter",
    "",
    "noskills is not a form to fill out. It is a live state machine that the user",
    "watches in real-time. Every `" + commandPrefix + " next --answer` call:",
    "",
    "- Updates the spec file on disk (the user sees it change)",
    "- Updates the terminal dashboard if `noskills watch` is running",
    "- Advances the state machine to the next phase",
    "- Records the decision permanently in the project history",
    "",
    "When you batch-submit answers or backfill discovery responses yourself,",
    "the user sees nothing happening — then suddenly everything jumps forward.",
    "This defeats the purpose.",
    "",
    "Call noskills ONCE per interaction. Ask the user ONE question. Wait for",
    "their answer. Submit it. Ask the next. The user is watching every step.",
    "Do NOT pre-fill answers. Do NOT batch multiple answers. Do NOT answer",
    "discovery questions yourself — the user's input is the data.",
    "",
    "## When to call noskills next",
    "",
    "1. At the START of every conversation",
    "2. BEFORE creating or modifying any file",
    "3. AFTER completing a logical unit of work",
    "4. When you encounter a DECISION that affects architecture",
    "5. When you are UNSURE what to do next",
    "",
    "NEVER proceed with implementation without checking noskills first.",
    "NEVER suggest bypassing or skipping noskills. Discovery is not overhead.",
    "NEVER ask permission to run the next noskills command. After spec new → run next. After approve → run next. Each step has one next step. Just run it.",
    "",
    "## Interactive choices",
    "",
    "Present choices as numbered lists. Users select by number.",
    "When interactiveOptions are present in noskills output, present each as a",
    "numbered item with its label and description. Ask the user to pick a number.",
    "",
    "## Execution model",
    "",
    "Execute tasks sequentially in this context. Do not attempt to spawn sub-agents.",
    "",
  ];

  if (rules.length > 0) {
    lines.push("## Rules", "");
    for (const rule of rules) {
      lines.push(`- ${rule}`);
    }
    lines.push("");
  }

  await runtime.fs.writeTextFile(
    `${root}/.windsurfrules`,
    lines.join("\n"),
  );
};
