// Code generated by "stringer -type RouteParameterType -trimprefix RouteParameterType"; DO NOT EDIT.

package httpfx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RouteParameterTypeHeader-0]
	_ = x[RouteParameterTypeQuery-1]
	_ = x[RouteParameterTypePath-2]
	_ = x[RouteParameterTypeBody-3]
}

const _RouteParameterType_name = "HeaderQueryPathBody"

var _RouteParameterType_index = [...]uint8{0, 6, 11, 15, 19}

func (i RouteParameterType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RouteParameterType_index)-1 {
		return "RouteParameterType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RouteParameterType_name[_RouteParameterType_index[idx]:_RouteParameterType_index[idx+1]]
}
