// Copyright 2023-present Eser Ozvataf and other contributors. All rights reserved. Apache-2.0 license.

/**
 * Shared AGENTS.md generator — produces the noskills instruction section
 * used by OpenCode, Codex CLI, and Copilot CLI adapters.
 *
 * The content is wrapped in `<!-- noskills:start -->` / `<!-- noskills:end -->`
 * markers so it can be safely replaced on subsequent syncs without disturbing
 * user-authored content in the same file.
 *
 * @module
 */

import type * as adapter from "../../adapter.ts";
import * as crossRuntime from "@eser/standards/cross-runtime";

// =============================================================================
// Constants
// =============================================================================

const AGENTS_MD = "AGENTS.md";
const NOS_SECTION_START = "<!-- noskills:start -->";
const NOS_SECTION_END = "<!-- noskills:end -->";

// =============================================================================
// Content Generators
// =============================================================================

const buildProtocol = (
  commandPrefix: string,
  options?: adapter.SyncOptions,
): string => {
  const lines = [
    "## noskills Protocol",
    "",
    "# Generated by noskills — do not edit manually",
    "",
    "### What is noskills",
    "",
    "This project uses noskills for state-driven orchestration.",
    "Do NOT read `.eser/rules/`, `.eser/specs/`, or concern files directly.",
    "noskills gives you exactly what you need via JSON output.",
    "",
    "### Protocol",
    "",
    `    ${commandPrefix} spec <name> next                           # get current instruction`,
    `    ${commandPrefix} spec <name> next --answer="your response"  # submit result and advance`,
    "",
    "Every noskills command that operates on a spec MUST include `spec <name>`.",
    `Never omit it. Use \`${commandPrefix} spec list\` to see available specs.`,
    "",
    "### Why noskills calls matter",
    "",
    "noskills is not a form to fill out. It is a live state machine that the user",
    "watches in real-time. Every `" + commandPrefix + " next --answer` call:",
    "",
    "- Updates the spec file on disk (the user sees it change)",
    "- Updates the terminal dashboard if `noskills watch` is running",
    "- Advances the state machine to the next phase",
    "- Records the decision permanently in the project history",
    "",
    "When you batch-submit answers or backfill discovery responses yourself,",
    "the user sees nothing happening — then suddenly everything jumps forward.",
    "This defeats the purpose.",
    "",
    "Call noskills ONCE per interaction. Ask the user ONE question. Wait for",
    "their answer. Submit it. Ask the next. The user is watching every step.",
    "Do NOT pre-fill answers. Do NOT batch multiple answers. Do NOT answer",
    "discovery questions yourself — the user's input is the data.",
    "",
    "### When to call noskills next",
    "",
    `You MUST call \`${commandPrefix} next\` in these situations:`,
    "",
    "1. At the **START** of every conversation (first thing you do)",
    "2. **BEFORE** creating or modifying any file (to verify you have an active task)",
    "3. **AFTER** completing a logical unit of work (to report progress)",
    "4. When you encounter a **DECISION** that affects architecture or scope",
    "5. When you are **UNSURE** what to do next",
    "",
    "NEVER proceed with implementation without checking noskills first.",
    "NEVER make architectural decisions independently — noskills routes them to the user.",
  ];

  if (!(options?.allowGit ?? false)) {
    lines.push(
      "",
      "### Git is read-only",
      "",
      "You MUST NOT run git write commands: commit, add, push, checkout, stash,",
      "reset, merge, rebase, cherry-pick. The user controls git. You control files.",
      "You MAY read from git: log, diff, status, show, blame.",
    );
  }

  lines.push(
    "",
    "### Interactive choices",
    "",
    "Present choices as numbered lists. Users select by number.",
    "When interactiveOptions are present in noskills output, present each as a",
    "numbered item with its label and description. Ask the user to pick a number.",
    "Use the `commandMap` to resolve the user's selection to a CLI command.",
    "",
    "### Decision principle: Explicit > Clever",
    "",
    "You NEVER skip steps, bypass questions, or make assumptions on behalf of the user.",
    "- Discovery questions → ask the user, don't answer yourself",
    "- Classification → ask the user, don't infer",
    "- Spec approval → ask the user, don't auto-approve",
    "- Task refinement → ask the user, don't self-assign",
    "- Rule promotion → ask the user, don't decide",
    'If you think something can be skipped, ASK "would you like to skip this?" — don\'t skip it.',
    "",
    "### Command execution",
    "",
    "When told to run a noskills command, execute it IMMEDIATELY. Do not explore,",
    "research, read source code, or plan first. The command output contains all the",
    "context you need. Exploring noskills internals wastes tokens and delays the user.",
    "",
    "### JSON output",
    "",
    "noskills returns JSON with a `phase` field and phase-specific instructions.",
    "The `meta` block contains resume context - use it to orient yourself,",
    "especially after compaction or at the start of a new session.",
    "Follow the `instruction` field. Use `transition` commands to advance state.",
    "",
  );

  return lines.join("\n");
};

const buildCoaching = (commandPrefix: string): string => {
  const lines = [
    "### Convention discovery",
    "",
    "When you discover a pattern, receive a correction, or identify a recurring",
    'preference from the user, ask: "Should this be a permanent rule for this',
    `project, or just for this task?" If permanent, run: \`${commandPrefix} rule add`,
    '"<description>"`. If just this task, note it and move on.',
    "Never write to `.eser/rules/` directly.",
    "",
    "### How to promote rules",
    "",
    "When a convention should be permanent, use the noskills CLI to register it:",
    "",
    `    ${commandPrefix} rule add "<description of the rule>"`,
    "",
    "This stores the rule in `.eser/rules/` and ensures it is synced to all",
    "coding tools on the next `noskills sync`. Never edit `.eser/rules/` directly.",
    "",
  ];

  return lines.join("\n");
};

const buildRules = (rules: readonly string[]): string => {
  const lines = [
    "### Active Rules",
    "",
  ];

  for (const rule of rules) {
    lines.push(`- ${rule}`);
  }

  lines.push("");

  return lines.join("\n");
};

const buildSection = (
  rules: readonly string[],
  commandPrefix: string,
  options?: adapter.SyncOptions,
): string => {
  const parts = [
    NOS_SECTION_START,
    buildProtocol(commandPrefix, options),
    buildCoaching(commandPrefix),
  ];

  if (rules.length > 0) {
    parts.push(buildRules(rules));
  }

  parts.push(NOS_SECTION_END);

  return parts.join("\n");
};

// =============================================================================
// Public API
// =============================================================================

/**
 * Generate or update the noskills section in AGENTS.md.
 *
 * Reads the existing file, replaces the content between the noskills markers
 * (or appends if markers are absent), and writes it back.
 */
export const syncAgentsMd = async (
  ctx: adapter.SyncContext,
  options?: adapter.SyncOptions,
): Promise<void> => {
  const filePath = `${ctx.root}/${AGENTS_MD}`;
  const section = buildSection(ctx.rules, ctx.commandPrefix, options);

  let content: string;

  try {
    content = await crossRuntime.runtime.fs.readTextFile(filePath);

    // Replace existing section or append
    const startIdx = content.indexOf(NOS_SECTION_START);
    const endIdx = content.indexOf(NOS_SECTION_END);

    if (startIdx !== -1 && endIdx !== -1) {
      content = content.slice(0, startIdx) + section +
        content.slice(endIdx + NOS_SECTION_END.length);
    } else {
      content = content.trimEnd() + "\n\n" + section + "\n";
    }
  } catch {
    content = section + "\n";
  }

  await crossRuntime.runtime.fs.writeTextFile(filePath, content);
};
