name: Integrity Pipeline

on:
  push:
    branches:
      - "**"

  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - "**"

  workflow_dispatch:
    inputs:
      run_checks:
        description: Run integrity checks
        required: false
        type: boolean

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-integrity
  cancel-in-progress: true

jobs:
  integration:
    uses: ./.github/workflows/integration.yml
    secrets: inherit
